DROP SCHEMA IF EXISTS main CASCADE;

CREATE SCHEMA main;

GRANT ALL ON SCHEMA main TO public;

CREATE TABLE
    main.video_session_details (
        id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        session_id varchar NOT NULL UNIQUE,
        meeting_link varchar UNIQUE,
        is_scheduled bool DEFAULT false NOT NULL,
        schedule_time timestamptz,
        is_archived bool DEFAULT false NOT NULL,
        archive_id varchar,
        upload_target varchar,
        start_time timestamptz,
        end_time timestamptz,
        created_on timestamptz DEFAULT current_timestamp NOT NULL,
        modified_on timestamptz,
        deleted bool DEFAULT false NOT NULL,
        created_by varchar,
        modified_by varchar,
        ext_id varchar,
        deleted_on timestamptz,
        deleted_by varchar,
        ext_metadata jsonb,
        CONSTRAINT "pk_video_session_details_id" PRIMARY KEY (id)
    );

CREATE TABLE
    main.session_attendees (
        id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        session_id varchar NOT NULL,
        attendee varchar NOT NULL,
        created_on timestamptz DEFAULT current_timestamp NOT NULL,
        modified_on timestamptz,
        deleted bool DEFAULT false NOT NULL,
        deleted_on timestamptz,
        deleted_by varchar,
        is_deleted bool DEFAULT false NOT NULL,
        ext_id varchar,
        ext_metadata jsonb,
        CONSTRAINT pk_session_attendees_id PRIMARY KEY (id)
    );

CREATE TABLE
    main.audit_logs (
        id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
        "action" varchar NOT NULL,
        action_type varchar NOT NULL,
        actor varchar,
        acted_at timestamptz DEFAULT current_timestamp,
        acted_entity varchar,
        "before" json,
        "after" json,
        reference varchar,
        ext_id varchar,
        ext_metadata jsonb,
        CONSTRAINT pk_audit_logs_id PRIMARY KEY (id)
    );